version: '3.8'

services:
  app:
    image: public.ecr.aws/f8h5l8q1/adyen/hospitality/api:latest
    container_name: adyen_app
    environment:
      - ACCEPT_LICENSE=Y
      - ASPNETCORE_ENVIRONMENT=%{{APP_ENVIRONMENT}}%
    depends_on:
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./appsettings.App.json:/app/appsettings.json
      - ./appsettings.App.json:/app/appsettings.Development.json
      - ./logs_app:/app/logs
    networks:
      - system-internal-network
