version: '3.8'

services:
  migrations:
    image: public.ecr.aws/f8h5l8q1/adyen/hospitality/migrations:latest
    container_name: adyen_migrations
    depends_on:
      systemdb:
        condition: service_healthy
    environment:
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=%{{POSTGRES_PASSWORD}}%
      - POSTGRES_DB=%{{POSTGRES_DB}}%
    env_file:
      - .env
    command:
      [
        "Server=systemdb;Port=5432;Database=%{{POSTGRES_DB}}%;UserId=master;Password=%{{POSTGRES_PASSWORD}}%"
      ]
    networks:
      - system-internal-network