version: '3'

services:
  webserver:
    container_name : ad-nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - internal-network
    volumes:
      - ./conf/:/etc/nginx/conf.d/:ro
      - ../certbot/www:/var/www/certbot/:ro
      - ../certbot/conf/:/etc/nginx/ssl/:ro
networks:
  internal-network:
    external: true
